import type { IconType } from 'react-icons'
import {
  HiOutlineAcademicCap,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineArrowPath,
  HiOutlineArrowRight,
  HiOutlineArrowTrendingUp,
  HiOutlineBattery50,
  HiOutlineBell,
  HiOutlineBolt,
  HiOutlineBookmark,
  HiOutlineBriefcase,
  HiOutlineCalendar,
  HiOutlineCamera,
  HiOutlineChartBar,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineChatBubbleLeftRight,
  HiOutlineClipboard,
  HiOutlineClock,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineCog6Tooth,
  HiOutlineCommandLine,
  HiOutlineCpuChip,
  HiOutlineCurrencyDollar,
  HiOutlineDevicePhoneMobile,
  HiOutlineDocumentArrowDown,
  HiOutlineDocumentText,
  HiOutlineEnvelope,
  HiOutlineExclamationTriangle,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFire,
  HiOutlineFolder,
  HiOutlineGlobeAlt,
  HiOutlineHome,
  HiOutlineInformationCircle,
  HiOutlineKey,
  HiOutlineLightBulb,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMicrophone,
  HiOutlineMoon,
  HiOutlineNewspaper,
  HiOutlinePaperClip,
  HiOutlinePause,
  HiOutlinePencil,
  HiOutlinePlay,
  HiOutlinePlus,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineScale,
  HiOutlineServer,
  HiOutlineShieldCheck,
  HiOutlineSignal,
  HiOutlineSparkles,
  HiOutlineSquares2X2,
  HiOutlineStar,
  HiOutlineStop,
  HiOutlineSun,
  HiOutlineTrash,
  HiOutlineUser,
  HiOutlineUsers,
  HiOutlineVideoCamera,
  HiOutlineWifi,
  HiOutlineXCircle,
  HiOutlineXMark,
} from 'react-icons/hi2'

export {
  HiOutlineAcademicCap,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineArrowPath,
  HiOutlineArrowRight,
  HiOutlineArrowTrendingUp,
  HiOutlineBattery50,
  HiOutlineBell,
  HiOutlineBolt,
  HiOutlineBookmark,
  HiOutlineBriefcase,
  HiOutlineCalendar,
  HiOutlineCamera,
  HiOutlineChartBar,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineChevronUp,
  HiOutlineChatBubbleLeftRight,
  HiOutlineClipboard,
  HiOutlineClock,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineCog6Tooth,
  HiOutlineCommandLine,
  HiOutlineCpuChip,
  HiOutlineCurrencyDollar,
  HiOutlineDevicePhoneMobile,
  HiOutlineDocumentArrowDown,
  HiOutlineDocumentText,
  HiOutlineEnvelope,
  HiOutlineExclamationTriangle,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFire,
  HiOutlineFolder,
  HiOutlineGlobeAlt,
  HiOutlineHome,
  HiOutlineInformationCircle,
  HiOutlineKey,
  HiOutlineLightBulb,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMicrophone,
  HiOutlineMoon,
  HiOutlineNewspaper,
  HiOutlinePaperClip,
  HiOutlinePause,
  HiOutlinePencil,
  HiOutlinePlay,
  HiOutlinePlus,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineScale,
  HiOutlineServer,
  HiOutlineShieldCheck,
  HiOutlineSignal,
  HiOutlineSparkles,
  HiOutlineSquares2X2,
  HiOutlineStar,
  HiOutlineStop,
  HiOutlineSun,
  HiOutlineTrash,
  HiOutlineUser,
  HiOutlineUsers,
  HiOutlineVideoCamera,
  HiOutlineWifi,
  HiOutlineXCircle,
  HiOutlineXMark,
}

export type { IconType }

/** Name → icon registry used by data-driven components (briefing, automations…). */
export const iconRegistry: Record<string, IconType> = {
  bell: HiOutlineBell,
  bolt: HiOutlineBolt,
  bookmark: HiOutlineBookmark,
  briefcase: HiOutlineBriefcase,
  calendar: HiOutlineCalendar,
  chart: HiOutlineChartBar,
  chat: HiOutlineChatBubbleLeftRight,
  check: HiOutlineCheckCircle,
  clock: HiOutlineClock,
  cloud: HiOutlineCloud,
  code: HiOutlineCodeBracket,
  cpu: HiOutlineCpuChip,
  document: HiOutlineDocumentText,
  download: HiOutlineDocumentArrowDown,
  email: HiOutlineEnvelope,
  folder: HiOutlineFolder,
  gauge: HiOutlineBolt,
  globe: HiOutlineGlobeAlt,
  home: HiOutlineHome,
  key: HiOutlineKey,
  light: HiOutlineLightBulb,
  microphone: HiOutlineMicrophone,
  moon: HiOutlineMoon,
  newspaper: HiOutlineNewspaper,
  pulse: HiOutlineArrowTrendingUp,
  refresh: HiOutlineArrowPath,
  robot: HiOutlineSparkles,
  rocket: HiOutlineRocketLaunch,
  scale: HiOutlineScale,
  server: HiOutlineServer,
  settings: HiOutlineCog6Tooth,
  shield: HiOutlineShieldCheck,
  signal: HiOutlineSignal,
  sparkles: HiOutlineSparkles,
  star: HiOutlineStar,
  sun: HiOutlineSun,
  target: HiOutlineAcademicCap,
  user: HiOutlineUser,
  users: HiOutlineUsers,
  wifi: HiOutlineWifi,
}
