import type { Automation } from '@/types'

export const AUTOMATIONS: Automation[] = [
  {
    id: 'auto1',
    name: 'Job Scan',
    description: 'Scans 4 boards every 2h, matches roles against your profile, and ranks new opportunities.',
    status: 'running',
    icon: 'briefcase',
    lastRun: 'Just now',
    nextRun: 'in ~1h 40m',
    runs: 128,
    category: 'career',
  },
  {
    id: 'auto2',
    name: 'Email Summary',
    description: 'Summarizes your inbox each morning and surfaces the 3 most important threads.',
    status: 'completed',
    icon: 'email',
    lastRun: '07:38',
    nextRun: 'Tomorrow 07:38',
    runs: 41,
    category: 'email',
  },
  {
    id: 'auto3',
    name: 'Calendar Optimization',
    description: 'Reorganizes meetings into focus blocks and protects your deep-work windows.',
    status: 'running',
    icon: 'calendar',
    lastRun: '07:10',
    nextRun: 'Continuous',
    runs: 214,
    category: 'productivity',
  },
  {
    id: 'auto4',
    name: 'Daily Briefing',
    description: 'Composes your morning briefing from memory, schedule, market and system state.',
    status: 'scheduled',
    icon: 'sparkles',
    lastRun: '07:45',
    nextRun: 'Tomorrow 07:45',
    runs: 32,
    category: 'productivity',
  },
  {
    id: 'auto5',
    name: 'Reminder Engine',
    description: 'Tracks deadlines, follow-ups and time-sensitive items across projects.',
    status: 'running',
    icon: 'clock',
    lastRun: 'Continuously',
    nextRun: 'Continuous',
    runs: 89,
    category: 'productivity',
  },
  {
    id: 'auto6',
    name: 'Resume Monitor',
    description: 'Watches for resume relevance drift and re-tailors for your top targets.',
    status: 'paused',
    icon: 'document',
    lastRun: 'Yesterday 22:14',
    nextRun: 'Paused',
    runs: 17,
    category: 'career',
  },
  {
    id: 'auto7',
    name: 'Knowledge Capture',
    description: 'Records facts, preferences and insights into your long-term memory graph.',
    status: 'running',
    icon: 'light',
    lastRun: 'Just now',
    nextRun: 'Continuous',
    runs: 412,
    category: 'memory',
  },
  {
    id: 'auto8',
    name: 'Intelligence Feed',
    description: 'Ranks research and market signals by relevance to your current projects.',
    status: 'running',
    icon: 'newspaper',
    lastRun: '4m ago',
    nextRun: 'in ~26m',
    runs: 156,
    category: 'intelligence',
  },
]
