"""Events package — typed registry + async event bus."""
from app.ai.events.bus import EventBus
from app.ai.events.registry import (
    AiThinking,
    BaseEvent,
    ChatCancelled,
    ChatChunk,
    ChatEnd,
    ChatError,
    ChatStarted,
    EventRegistry,
    MemoryConsolidated,
    MemoryUpdated,
    PlannerEnd,
    PlannerStep,
    PlannerToolCall,
    SystemEvent,
    SystemMetrics,
    VoiceEnd,
    VoiceStarted,
    VoiceTranscript,
    build_default_registry,
)

__all__ = [
    "AiThinking",
    "BaseEvent",
    "ChatCancelled",
    "ChatChunk",
    "ChatEnd",
    "ChatError",
    "ChatStarted",
    "EventBus",
    "EventRegistry",
    "MemoryConsolidated",
    "MemoryUpdated",
    "PlannerEnd",
    "PlannerStep",
    "PlannerToolCall",
    "SystemEvent",
    "SystemMetrics",
    "VoiceEnd",
    "VoiceStarted",
    "VoiceTranscript",
    "build_default_registry",
]
